version: 2.1

orbs:
  gcp-gcr: circleci/gcp-gcr@0.13.0

jobs:
  deploy_cloud_run:
    machine:
      docker_layer_caching: true
      resource_class: large
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: circleci-demo-ip-ranges
          tag: '${CIRCLE_SHA1}'
      - gcp-gcr/push-image:
          image: circleci-demo-ip-ranges
          tag: '${CIRCLE_SHA1}'
      - run:
          name: Deploy to Google Cloud run
          command: >-
            gcloud run deploy circleci-demo-ip-ranges
            --platform=managed --region=us-east1 --allow-unauthenticated
            --image=gcr.io/${GOOGLE_PROJECT_ID}/circleci-demo-ip-ranges:${CIRCLE_SHA1}

workflows:
  test_and_deploy: 
    jobs:
      - deploy_cloud_run:
          context: deploy-cloud-run
          filters:
            branches:
              only:
                - master
