version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0

jobs:
  install_cypress:
    executor: cypress/browsers-chrome77
    steps:
      - checkout
      - cypress/install

  cypress_with_ip_ranges:
    executor: cypress/browsers-chrome77
    circleci_ip_ranges: true
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Show IP address
          command: curl -s https://checkip.amazonaws.com/
      - run: npm run cypress

  cypress_without_ip_ranges:
    executor: cypress/browsers-chrome77
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Show IP address
          command: curl -s https://checkip.amazonaws.com/
      - run: npm run cypress

workflows:
  test_and_deploy: 
    jobs:
      - install_cypress
      - cypress_with_ip_ranges:
          requires:
            - install_cypress
      - cypress_without_ip_ranges:
          requires:
            - install_cypress
