version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0
  node: circleci/node@5.0.0
  heroku: circleci/heroku@1.2.6

jobs:
  deploy_heroku:
    machine: true
    steps:
    - checkout
    - heroku/install
    - run:
        name: Deploy to heroku
        command: |
          heroku container:push web -a $HEROKU_APP_NAME
          heroku container:release web -a $HEROKU_APP_NAME

  install_cypress:
    executor: cypress/browsers-chrome77
    steps:
      - checkout
      - cypress/install

  cypress_with_ip_ranges:
    executor: cypress/browsers-chrome77
    circleci_ip_ranges: true
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Show IP address
          command: curl -s https://checkip.amazonaws.com/
      - run: npm run cypress

  cypress_without_ip_ranges:
    executor: cypress/browsers-chrome77
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Show IP address
          command: curl -s https://checkip.amazonaws.com/
      - run: npm run cypress

workflows:
  build_and_deploy_heroku:
    jobs:
      - node/test:
          run-command: test:ci
          test-results-for: jest
      - node/run:
          name: build
          npm-run: build
      - deploy_heroku:
          filters:
            branches:
              only: master

  cypress: 
    jobs:
      - install_cypress
      - cypress_with_ip_ranges:
          requires:
            - install_cypress
      - cypress_without_ip_ranges:
          requires:
            - install_cypress
          filters:
            branches:
              only: master
